apiVersion: v1
kind: Service
metadata:
  name: compliancex-web
spec:
  selector:
    app: compliancex-web
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: compliancex-web
spec:
  selector:
    matchLabels:
      app: compliancex-web
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: compliancex-web
    spec:
      hostNetwork: true
      containers:
      - name: compliancex-web
        image: nginx:1.18-alpine-perl
        ports:
        - containerPort: 80
