apiVersion: v1
kind: Service
metadata:
  name: compliancex-rabbitmq
spec:
  selector:
    app: compliancex-rabbitmq
  ports:
    - name: tcp
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: compliancex-rabbitmq
spec:
  selector:
    matchLabels:
      app: compliancex-rabbitmq
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: compliancex-rabbitmq
    spec:
      hostNetwork: true
      containers:
      - name: compliancex-rabbitmq
        image: umair841/demo
        ports:
        - containerPort: 5000


